import "./globals.css";

export const metadata = {
  title: "Zuri.corp",
  description: "Generated by zuri",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
